-- Ledgerly schema. Loaded first by the db image (01-schema.sql) and by the tests.
-- Money is integer cents; timestamps are timestamptz in UTC.

-- "This month" means the UTC calendar month everywhere (app, seed and support views).
DO $$
BEGIN
  EXECUTE format('ALTER DATABASE %I SET timezone TO %L', current_database(), 'UTC');
END
$$;
SET TIME ZONE 'UTC';

CREATE TABLE plans (
  id text PRIMARY KEY,
  name text NOT NULL,
  monthly_price_cents integer NOT NULL,
  annual_price_cents integer NOT NULL,
  -- NULL means unlimited.
  monthly_invoice_limit integer
);

INSERT INTO plans (id, name, monthly_price_cents, annual_price_cents, monthly_invoice_limit) VALUES
  ('starter', 'Starter', 0, 0, 5),
  ('pro', 'Pro', 2900, 29000, 200),
  ('business', 'Business', 9900, 99000, NULL);

CREATE TABLE customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_id text NOT NULL UNIQUE CHECK (external_id LIKE 'cus\_%'),
  company_name text NOT NULL,
  contact_name text NOT NULL,
  contact_email text NOT NULL,
  country char(2) NOT NULL,
  timezone text NOT NULL,
  currency char(3) NOT NULL CHECK (currency IN ('EUR', 'USD')),
  -- VAT applied to the customer's own invoices, in basis points (1900 = 19%).
  default_vat_rate_bps integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- The customer's card on file. Fake: only brand, last four digits and expiry are kept.
CREATE TABLE cards (
  customer_id bigint PRIMARY KEY REFERENCES customers (id),
  brand text NOT NULL,
  last4 char(4) NOT NULL,
  exp_month integer NOT NULL CHECK (exp_month BETWEEN 1 AND 12),
  exp_year integer NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL UNIQUE REFERENCES customers (id),
  plan_id text NOT NULL REFERENCES plans (id),
  billing_interval text NOT NULL CHECK (billing_interval IN ('month', 'year')),
  status text NOT NULL CHECK (status IN ('active', 'past_due', 'canceled')),
  current_period_start timestamptz NOT NULL,
  current_period_end timestamptz NOT NULL,
  canceled_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE SEQUENCE billing_invoice_number_seq START 10001;

-- What Ledgerly charges the customer.
CREATE TABLE billing_invoices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number text NOT NULL UNIQUE DEFAULT ('LB-' || nextval('billing_invoice_number_seq')),
  customer_id bigint NOT NULL REFERENCES customers (id),
  description text NOT NULL,
  -- Negative for credits (e.g. unused time after a downgrade).
  amount_cents integer NOT NULL,
  currency char(3) NOT NULL,
  status text NOT NULL CHECK (status IN ('paid', 'open', 'uncollectible', 'void')),
  period_start timestamptz,
  period_end timestamptz,
  -- Dunning state while the invoice is open after a failed payment.
  retry_count integer NOT NULL DEFAULT 0,
  dunning_started_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  billing_invoice_id bigint NOT NULL REFERENCES billing_invoices (id),
  customer_id bigint NOT NULL REFERENCES customers (id),
  amount_cents integer NOT NULL,
  currency char(3) NOT NULL,
  status text NOT NULL CHECK (status IN ('succeeded', 'failed')),
  failure_code text,
  card_last4 char(4) NOT NULL,
  attempted_at timestamptz NOT NULL DEFAULT now()
);

-- Scheduled retries of a failed billing invoice payment.
CREATE TABLE payment_retries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  billing_invoice_id bigint NOT NULL REFERENCES billing_invoices (id),
  customer_id bigint NOT NULL REFERENCES customers (id),
  attempt integer NOT NULL,
  scheduled_for timestamptz NOT NULL,
  status text NOT NULL CHECK (status IN ('scheduled', 'succeeded', 'failed', 'canceled')),
  payment_id bigint REFERENCES payments (id),
  created_at timestamptz NOT NULL DEFAULT now()
);

-- What the customer sends their own clients.
CREATE TABLE invoices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES customers (id),
  number text NOT NULL,
  client_name text NOT NULL,
  client_email text NOT NULL,
  issue_date date NOT NULL,
  due_date date NOT NULL,
  status text NOT NULL CHECK (status IN ('draft', 'sent', 'paid')),
  notes text NOT NULL DEFAULT '',
  currency char(3) NOT NULL,
  subtotal_cents integer NOT NULL,
  vat_cents integer NOT NULL,
  total_cents integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  sent_at timestamptz,
  paid_at timestamptz,
  deleted_at timestamptz,
  UNIQUE (customer_id, number)
);

CREATE TABLE invoice_lines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id bigint NOT NULL REFERENCES invoices (id),
  position integer NOT NULL,
  description text NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price_cents integer NOT NULL CHECK (unit_price_cents >= 0),
  vat_rate_bps integer NOT NULL CHECK (vat_rate_bps >= 0)
);

CREATE INDEX invoices_customer_created_idx ON invoices (customer_id, created_at);
CREATE INDEX billing_invoices_customer_idx ON billing_invoices (customer_id, created_at);
CREATE INDEX payments_customer_idx ON payments (customer_id, attempted_at);
CREATE INDEX payment_retries_due_idx ON payment_retries (status, scheduled_for);
