// The 12 seeded Ledgerly customers. The named personas each show one planted bug or one
// data question (see PLANTED_BUGS.md and the README).

export type Scenario =
  | 'paid' // pays every period on time
  | 'free' // Starter, never billed
  | 'b1-upgrade' // cus_alder: upgraded Pro → Business late in the period (B1)
  | 'pending-retry' // cus_fjord: card declined, retry 2 of 3 is scheduled
  | 'b2-card-update' // cus_lumen: card updated after 2 failed retries, then canceled (B2)
  | 'recovered' // cus_oakridge: a failed payment that succeeded on retry, months ago
  | 'canceled'; // cus_meridian: canceled their subscription themselves

export interface CustomerSpec {
  id: number;
  externalId: string;
  companyName: string;
  contactName: string;
  contactEmail: string;
  country: string;
  timezone: string;
  currency: 'EUR' | 'USD';
  vatRateBps: number;
  plan: 'starter' | 'pro' | 'business';
  interval: 'month' | 'year';
  scenario: Scenario;
  /** Days since the current billing period started. */
  periodDay: number;
  /** Card last four digits; null for no card on file. */
  cardLast4: string | null;
  invoiceCount: number;
  services: [description: string, unitPriceCents: number][];
}

export const CUSTOMERS: CustomerSpec[] = [
  {
    id: 1,
    externalId: 'cus_maple',
    companyName: 'Maple & Moss Design',
    contactName: 'Avery Maple',
    contactEmail: 'avery@maplemoss.example',
    country: 'CA',
    timezone: 'America/Toronto',
    currency: 'USD',
    vatRateBps: 0,
    plan: 'starter',
    interval: 'month',
    scenario: 'free',
    periodDay: 9,
    cardLast4: null,
    invoiceCount: 20,
    services: [
      ['Logo design', 45000],
      ['Brand guidelines', 80000],
      ['Illustration (per piece)', 15000],
      ['Design consultation (hour)', 9000],
    ],
  },
  {
    id: 2,
    externalId: 'cus_alder',
    companyName: 'Alder Analytics d.o.o.',
    contactName: 'Nika Alder',
    contactEmail: 'nika@alderanalytics.example',
    country: 'SI',
    timezone: 'Europe/Ljubljana',
    currency: 'EUR',
    vatRateBps: 2200,
    plan: 'business',
    interval: 'month',
    scenario: 'b1-upgrade',
    periodDay: 25,
    cardLast4: '4242',
    invoiceCount: 30,
    services: [
      ['Data pipeline setup', 240000],
      ['Dashboard development (day)', 64000],
      ['Monthly analytics retainer', 150000],
      ['Workshop', 90000],
    ],
  },
  {
    id: 3,
    externalId: 'cus_fjord',
    companyName: 'Fjord Freight AS',
    contactName: 'Ingrid Fjeld',
    contactEmail: 'ingrid@fjordfreight.example',
    country: 'NO',
    timezone: 'Europe/Oslo',
    currency: 'EUR',
    vatRateBps: 2500,
    plan: 'pro',
    interval: 'month',
    scenario: 'pending-retry',
    periodDay: 2,
    cardLast4: '0002',
    invoiceCount: 20,
    services: [
      ['Pallet transport Oslo–Bergen', 42000],
      ['Express courier', 8500],
      ['Warehousing (pallet, month)', 3500],
      ['Customs handling', 12000],
    ],
  },
  {
    id: 4,
    externalId: 'cus_lumen',
    companyName: 'Lumen Estudio SL',
    contactName: 'Lucía Romero',
    contactEmail: 'lucia@lumenestudio.example',
    country: 'ES',
    timezone: 'Europe/Madrid',
    currency: 'EUR',
    vatRateBps: 2100,
    plan: 'pro',
    interval: 'month',
    scenario: 'b2-card-update',
    periodDay: 20,
    cardLast4: '9995',
    invoiceCount: 15,
    services: [
      ['Product photography (half day)', 60000],
      ['Retouching (per image)', 2500],
      ['Studio rental (hour)', 7500],
    ],
  },
  {
    id: 5,
    externalId: 'cus_kestrel',
    companyName: 'Kestrel Kaffee GmbH',
    contactName: 'Jonas Becker',
    contactEmail: 'jonas@kestrelkaffee.example',
    country: 'DE',
    timezone: 'Europe/Berlin',
    currency: 'EUR',
    vatRateBps: 1900,
    plan: 'business',
    interval: 'month',
    scenario: 'paid',
    periodDay: 14,
    cardLast4: '4444',
    invoiceCount: 60,
    services: [
      ['Espresso beans 1 kg', 2450],
      ['Filter coffee 500 g', 1250],
      ['Barista training (hour)', 6500],
      ['Grinder service', 8900],
      ['Oat milk case', 1875],
    ],
  },
  {
    id: 6,
    externalId: 'cus_tidewater',
    companyName: 'Tidewater Consulting LLC',
    contactName: 'Marcus Hale',
    contactEmail: 'marcus@tidewaterconsulting.example',
    country: 'US',
    timezone: 'America/New_York',
    currency: 'USD',
    vatRateBps: 0,
    plan: 'pro',
    interval: 'month',
    scenario: 'paid',
    periodDay: 11,
    cardLast4: '1881',
    invoiceCount: 25,
    services: [
      ['Strategy session (hour)', 25000],
      ['Market research report', 350000],
      ['Monthly advisory retainer', 400000],
    ],
  },
  {
    id: 7,
    externalId: 'cus_sable',
    companyName: 'Sable & Fils SARL',
    contactName: 'Camille Sable',
    contactEmail: 'camille@sablefils.example',
    country: 'FR',
    timezone: 'Europe/Paris',
    currency: 'EUR',
    vatRateBps: 2000,
    plan: 'business',
    interval: 'year',
    scenario: 'paid',
    periodDay: 201,
    cardLast4: '5100',
    invoiceCount: 40,
    services: [
      ['Furniture restoration', 180000],
      ['Upholstery (per seat)', 22000],
      ['Delivery Île-de-France', 9000],
      ['Wood finish consultation', 12000],
    ],
  },
  {
    id: 8,
    externalId: 'cus_oakridge',
    companyName: 'Oakridge Studio Inc.',
    contactName: 'Priya Natarajan',
    contactEmail: 'priya@oakridgestudio.example',
    country: 'US',
    timezone: 'America/Chicago',
    currency: 'USD',
    vatRateBps: 0,
    plan: 'business',
    interval: 'month',
    scenario: 'recovered',
    periodDay: 6,
    cardLast4: '8210',
    invoiceCount: 50,
    services: [
      ['Web development (day)', 120000],
      ['UX audit', 450000],
      ['Hosting & maintenance (month)', 35000],
      ['Copywriting (page)', 30000],
    ],
  },
  {
    id: 9,
    externalId: 'cus_brightline',
    companyName: 'Brightline Elektro GmbH',
    contactName: 'Sabine Krüger',
    contactEmail: 'sabine@brightline.example',
    country: 'DE',
    timezone: 'Europe/Berlin',
    currency: 'EUR',
    vatRateBps: 1900,
    plan: 'pro',
    interval: 'year',
    scenario: 'paid',
    periodDay: 88,
    cardLast4: '0005',
    invoiceCount: 15,
    services: [
      ['Electrical inspection', 29000],
      ['Wallbox installation', 145000],
      ['Labour (hour)', 7200],
    ],
  },
  {
    id: 10,
    externalId: 'cus_pinecrest',
    companyName: 'Pinecrest Prevodi s.p.',
    contactName: 'Tadej Kovač',
    contactEmail: 'tadej@pinecrest.example',
    country: 'SI',
    timezone: 'Europe/Ljubljana',
    currency: 'EUR',
    vatRateBps: 2200,
    plan: 'starter',
    interval: 'month',
    scenario: 'free',
    periodDay: 17,
    cardLast4: null,
    invoiceCount: 10,
    services: [
      ['Translation EN–SL (page)', 2800],
      ['Proofreading (page)', 1200],
      ['Certified translation', 6500],
    ],
  },
  {
    id: 11,
    externalId: 'cus_meridian',
    companyName: 'Meridian Yoga',
    contactName: 'Élise Martin',
    contactEmail: 'elise@meridianyoga.example',
    country: 'FR',
    timezone: 'Europe/Paris',
    currency: 'EUR',
    vatRateBps: 2000,
    plan: 'pro',
    interval: 'month',
    scenario: 'canceled',
    periodDay: 47,
    cardLast4: '4242',
    invoiceCount: 8,
    services: [
      ['Corporate yoga class', 18000],
      ['Ten-class pass', 15000],
    ],
  },
  {
    id: 12,
    externalId: 'cus_quarry',
    companyName: 'Quarry Lane Bikes',
    contactName: 'Dan Okafor',
    contactEmail: 'dan@quarrylanebikes.example',
    country: 'US',
    timezone: 'America/Denver',
    currency: 'USD',
    vatRateBps: 0,
    plan: 'pro',
    interval: 'month',
    scenario: 'paid',
    periodDay: 23,
    cardLast4: '1117',
    invoiceCount: 12,
    services: [
      ['Full bike service', 14000],
      ['Wheel truing', 3500],
      ['Fleet maintenance (bike)', 9000],
    ],
  },
];

export const CLIENTS: [name: string, email: string][] = [
  ['Northwind Bakery', 'accounts@northwind-bakery.example'],
  ['Harbor Lights Hotel', 'billing@harborlights.example'],
  ['Copperleaf Dental', 'office@copperleaf.example'],
  ['Bluebird Books', 'hello@bluebirdbooks.example'],
  ['Atlas Logistics', 'ap@atlaslogistics.example'],
  ['Granite Peak Gym', 'admin@granitepeak.example'],
  ['Silverline Architects', 'finance@silverline.example'],
  ['Orchard Street Café', 'team@orchardcafe.example'],
  ['Redwood Legal', 'billing@redwoodlegal.example'],
  ['Cobalt Robotics', 'ap@cobaltrobotics.example'],
  ['Lighthouse Clinic', 'admin@lighthouseclinic.example'],
  ['Saffron Kitchen', 'owner@saffronkitchen.example'],
  ['Evergreen School', 'office@evergreenschool.example'],
  ['Polar Ice Rink', 'info@polarice.example'],
];
